# Lecture 2, Solving ODE's

There are a number of question marks "?" throughout the markdown section of this notebook. You are responsible for filling those sections in. 

**Overview:**
* Solving initial value problems, a simple example
* Survey of methods.
* Errors and numerical stability
    * Reading: Newman chapter 4.

**Next Lecture:** Solving systems of coupled ODE's and Newtons 2nd law.

---

## Simple Example, an RC circuit. 
We have a simple RC circuit, as shown below. After a long charge with the switch in position 1 it is flipped to position 2. What is the time dependence of the charge across $C$?

![RC circuit](./figs/Lecture2_circuit.png)











Using Kirchoff's laws, determine the 1st order ODE we need to solve for $Q(t)$:

$$\frac{dQ}{dt} = ? $$

What is the closed form solution of this equation:
$$ Q(t) = ? $$

In this case the problem was easy to solve. However, there are many cases of such problems, formulated as ordinary differential equations, where the solution is not so easy (or even impossible) to find. So how might we approximate the solution to this problem and solve numerically?

An obvious thing to try is to Taylor expand $Q(t)$ for small $\Delta t$ around $t=0$

$$ Q(\Delta t) = Q(0) + \frac{dQ}{dt}\Delta t + \frac{1}{2}\frac{d^2Q}{dt^2}(\Delta t)^2 + \dots $$

If $\Delta t$ is very small, then it is usually a good approximation to ignore terms that involve second and higher powers of $\Delta t$

$$ Q(\Delta t) \approx Q(0) + \frac{dQ}{dt}\Delta t$$

and we know the functional form of the derivative. It is given by the original ODE! We now have:

$$ Q(t + \Delta t) \approx Q(t) - ?? \Delta t $$

This is the general strategy for solving ODE's on a computer. By Taylor expanding we have taken a problem defined on a continuous variable $t$, and transformed it to an approximate problem defined on a discrete variable $\Delta t$. This is always necessary since computers only operate on discrete quantities.

---

## Methods for ODE's

To understand our approximate methods, we work with a single ordinary differential equation.
$$\frac{dx}{dt}=g(x,t)$$
where $x(t)$ is the solution we seek and $g(x,t)$ is a well-behaved but otherwise arbitrary function.

If we know $x(t)$ we could determine $g(t+\Delta t)$ from the Taylor series:
$$x(t+\Delta t) = x(t) + \frac{dx}{dt}\Delta t + \frac{d^2x}{dt^2}\frac{(\Delta t)^2}{2!} + \frac{d^3x}{dt^3}\frac{\Delta t^2}{3!} + \dots$$

## Euler's method

$$x(t_{n+1}) = x(t_{n}) + g(x_n,t_n)\Delta t +O[(\Delta t)^2].$$

where $x_n$ is the the value of our solution at time point $t_n$ and discrete step $n$.

## Improved accuracy: Runge-Kutta methods

### RK2:

$$
\begin{align}
k_1 &= \Delta t g(x_n, t_n)\\
k_2 &= \Delta t g(x_n+1/2k_1, t_n+\Delta t/2)\\
x(t_{n+1}) &= x(t_n) + k_2
\end{align}
$$


### RK4:

$$
\begin{align}
k_1 &= \Delta t g(x_n, t_n)\\
k_2 &= \Delta t g(x_n+1/2k_1, t_n+\Delta t/2)\\
k_3 &= \Delta t g(x_n+1/2k_2, t_n+\Delta t/2)\\
k_4 &= \Delta t g(x_n+k_3, t_n+\Delta t)\\
x(t_{n+1}) &= x(t_n) + \frac{1}{6}(k_1+2k_2+2k_3+k_4)
\end{align}
$$

***
## Pseudocode (for all methods):
### Initialization
* Assign initial values and constants: $x\left(0\right)$, $\Delta t$, any constants in $g(x,t)$.
* Set the number of time steps and the initial value of time.

### Calculation
* At time step $x_i$, calculate $x_{i+1}$ and $t_{i+1}$ at step $i+1$.
* Increase to $t_i$ to the next time step $t_{i+1} = t_i + \Delta t$.
* repeat for $n-1$ time steps.

### Analysis
* store the values for $x_i$ and $t_i$ in a file. 
* plot results or use in subsequent calculation.

***

# Exercise

1. Define a function for the exact solution of our simple RC circuit, $Q(t)$. This will be used to test the accuracy of our numerical methods. Plot $Q(t)$ for a fixed $RC$.

2. Define another function to find the solution of our differential equation numerically using an RK2 method.

3. Using the functions in 1 and 2, plot the exact and approximate solutions over-top of each other for the range of time from $t$ = 0 to 10, and using the parameters: $R=1$, $C=1$, $Q_0=1$, and $\Delta t$ = 0.1 .

4. Finally, create a function to calculate and then plot the total cumulative error of our approximate solution as a function of the step size $\Delta t$ from $\Delta t$ = 0.001 to 10 over a time from $t$ = 0 to 10. How does this plot change with increasing final time?



**You will find some starter code in the cells below**


In [1]:
# it is good practice to include all import statements in the first code cell at the top of your workbook or script.
import numpy as np
import matplotlib.pyplot as plt

# this is a so called "magic" function that allows for interactive plotting, 
# you will see below when we plot the results
%matplotlib notebook  

In [4]:
#  Modify this function to output the exact solution for Q(t) from above
# Q0 and t0 are the initial charge and time

# Note the default argument for t0 = 0. Using this means we only have to pass a value for t0 to the function
# if we want something different from 0

def exact(t, R, C, Q0, t0 =0.0):
    # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! exact solution here  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Q = Q0*np.exp(-t/R/C)
    return Q

? np.zeros

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
      

In [ ]:
# Modify this function to implement an RK2 method for our RC circuit ODE

# note the template here is for one way to do this, and not necessarily the best way.
# I encourage you to try and think of a better and more general way to write this Euler method function.

def approx_rk2(dt, t_final, R, C, Q0, t0=0.0):
    
    # number of time steps, nust be an integer
    n  = int(t_final/dt) 
    
    #initialize some empty lists to store our data and time steps
    Q_list = np.zeros(n)
    t_list = np.zeros(n)
    
    # the main loop over all time steps
    for ii in range(n):
        if ii == 0.0:
            # set initial conditions at time zero
            Q = Q0
            t = t0
        else :
            # !!!!!!!!!!!!!!!!!!!!!!   RK2 method here  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            
            k1 = 
            k2 = 
            
            # update value of Q at each time step and step time by dt
            Q+=
            t+=
            
            
        # use append to add on to the end of a list
        Q_list.append(Q)
        t_list.append(t)
    
    # we turn the lists into numpy arrays before returning
    
#    Q_list = np.array(Q_list)
 #   t_list = np.array(t_list)
    
    return t_list, Q_list

In [6]:
    Q_list = np.zeros(100)
    t_list = np.zeros(100)
    t_list


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Define our constants
Q0, t0 = 10, 0.0
t_final, dt = 10, 0.1
R, C = 1, 1 

#create an array with 1000 equally spaced points spanning t0 to _final to pass to our exact expression
t = np.linspace(t0,t_final,1000) 

# Calculate the exact solution
Q_exact = 


#Call our  approximate function, this returns function values and time points 
t_approx, Q_approx = 

In [ ]:
# Generate plots 
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(t, Q_exact, linestyle = '-', label = "exact")

# plot approximate solution (use discrete points with no connecting line)
ax.plot()

plt.legend()
plt.xlabel("time (units)")
plt.ylabel("Capacitor charge (units)")

In [ ]:
# Write a function to calculate the cumulative error
# hint, try reading the help file on np.sum

def cumulative_error(dt, t_final, R, C, Q0):
    # error = abs(approximate - exact)

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.sum(a)
print(b)

In [ ]:
? np.sum

In [ ]:
plt.figure()
plt.plot([1,2,3],[1,2,3])
plt.show()
